blockDeployment:
  - accounts: 
    - demo-prod-west-cluster
    - prod-eu
    application:
    - potato-facts
  - accounts: 
    - demo-staging-cluster
    - prod-east
    application:
    - 'potato-lies'