apiVersion: v1
kind: Service
metadata:
  labels:
    app: potato-facts
  name: potato-facts-external

spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: gate-tcp
    port: 80
    protocol: TCP
    targetPort: 8086
  selector:
    app: potato-facts
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: potato-facts-cluster-svc
  labels:
    app: potato-facts-2
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: potato-facts-2
  #    name: prth-test
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP













