name: Deploy my latest version

on:
  push: # What triggers a deployment. For example, `push`.
    branches:
      - main # What branch triggers a deployment. For example, `main`.

jobs:
  build:
    name: deploy from main CLI
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deployment
        id: armory
        uses: armory/cli-deploy-action@main
        with:
          clientId: ${{ secrets.CDAAS_CLIENT_ID }}  # "61ihoLa6dkk5SRwAy232H0TJk1xTBbK6"
          clientSecret:  ${{ secrets.CDAAS_CLIENT_SECRET }} #Client secret that you created in the Armory Cloud Console that has been encrypted with GitHub's encrypted secrets.
          path-to-file: "/deploy.yml"
          applicationName: "potato-facts-main4ps"
      - name: echo-ID
        uses: peter-evans/commit-comment@v2
        with:
          sha: ${{github.sha}}
          message: |
            Deployment URL - ${{steps.armory.outputs.DEPLOYMENT_ID}}

#        run: |
#          echo ${{join(steps.armory.outputs.*, '\n')}}
